services:
  mongo:
    image: edgedb/edgedb:4
    restart: unless-stopped
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
    container_name: narrative_craft_mongo
    ports:
      - '5656:5656'
    volumes:
      - edge_data:/var/lib/edgedb/data
volumes:
  edge_data:
